spring.application.name=adm-assembleia
version=v1
server.servlet.context-path=/adm-assembleia/api/${version}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/admassembleiadb?currentSchema=admassembleia
spring.datasource.username=postgres
spring.datasource.password=postgres

springdoc.api-docs.path=/v3/api-doc
springdoc.swagger-ui.path=/swagger-ui

validador.cpf.client=https://user-info.herokuapp.com
